added the proton electronic energy firework
hackingmaterials/atomate pull request #758
Opened 2022-06-26 20:40 UTC by rdguha1995

## Summary

<Short few sentences, and summary of the major changes in bullet
points>

* Feature 1
* Feature 2
* Fix 1
* Fix 2

## TODO (if any)

<If this is a work-in-progress, write something about what else needs
to be done>

* Feature 1 supports a, but not b.

2022-06-28 23:18 UTC, samblau commented
@Zhuoying, please trigger the tests here

2022-07-01 03:02 UTC, Zhuoying commented
Thanks @samblau for the reminder. -Just trigger tests and it looks like passing the tests. 
Since it is related to QChem jobs, could you please review it when you are available? 
Please free feel to ping me if you need anything from my side. Thanks.

2022-07-01 14:43 UTC, samblau requested changes
Very minor changes suggested. Once they are made, this should be ready to merge!

2022-07-05 17:02 UTC, rdguha1995 commented on atomate/qchem/fireworks/tests/test_core.py
> +    def test_ProtonEnergyFW_not_defaults(self):
Thanks @samblau for the comments! I have implemented them and I think this should be ready to merge. Thanks @Zhuoying for all the help.

2022-07-08 17:03 UTC, rdguha1995 commented
Hey @Zhuoying! It would be great if you can take some time to merge this. I have implemented all the changes suggested by @samblau

2022-07-12 16:42 UTC, rdguha1995 commented
Hey @Zhuoying . Just circling back on this. Can you take some time out for merging this?

Thanks a lot!

2022-07-12 18:24 UTC, rdguha1995 commented
Hey @Zhuoying , can you help me with the current errors?  They are not in codes I have played with. What would be the best way to solve this?

2022-07-14 00:02 UTC, Zhuoying commented
@rdguha1995 Yes, the error seems to be induced by the recent change in pymatgen.io.feff (https://github.com/materialsproject/pymatgen/blob/c1e47a78bcf5d4f23b11b83570adb861f47cb183/pymatgen/io/feff/sets.py#L357), not your part. 
I will merge your PR for now. And fix the error in another PR. Thanks!

2022-07-14 00:03 UTC, merged

2022-07-27 22:45 UTC, janosh commented
CI fix submitted in #760.